import { Injectable } from '@angular/core';
import { profile } from 'console';

@Injectable({
  providedIn: 'root'
})
export class AllCardsService {
 CardsInfo = [  
    {
      featuredBtn: true,
      For: 'For Sale',
      imgLink: '../../assets/Imges/Header/CardImges/F1.jpg',
      alt: 'Luxury family house villa for sale',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 110,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-4.jpg',
      profileName: 'john Doe',
      uploadmonth: 2,
    },
    {
      featuredBtn: false,
      For: 'For Rent',
      imgLink: '../../assets/Imges/Header/CardImges/F2.jpg',
      alt: 'Luxury family house villa for rent',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 150,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-6.jpg',
      profileName: 'Maria Williams',
      uploadmonth: 2,
    },
    {
      featuredBtn: false,
      For: 'For Sale',
      imgLink: '../../assets/Imges/Header/CardImges/F3.jpg',
      alt: 'Another luxury family house villa for sale',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 150,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-3.jpg',
      profileName: 'Martina Williams',
      uploadmonth: 4,
    },
    {
      featuredBtn: true,
      For: 'For Rent',
      imgLink: '../../assets/Imges/Header/CardImges/F4.jpg',
      alt: 'Featured luxury family house villa for rent',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 150,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-6.jpg',
      profileName: 'Maria Williams',
      uploadmonth: 1,
    },
    {
      featuredBtn: true,
      For: 'For Sale',
      imgLink: '../../assets/Imges/Header/CardImges/F5.jpg',
      alt: 'Featured luxury family house villa for sale',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 150,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-6.jpg',
      profileName: 'Maria Williams',
      uploadmonth: 6,
    },
    {
      featuredBtn: false,
      For: 'For Rent',
      imgLink: '../../assets/Imges/Header/CardImges/F6.jpg',
      alt: 'Luxury family house villa for rent',
      header: 'Real Luxury Family House Villa',
      location: 'Est St, 77 - Central Park South, NYC',
      bedrooms: 6,
      bathrooms: 3,
      area: 720,
      garages: 2,
      price: '$ 135,000',
      profileImg: '../../../assets/Imges/StaticImg/CardImges/ts-6.jpg',
      profileName: 'Maria Williams',
      uploadmonth: 2,
    },
  ];
  constructor() { }
}
